version: "3.7"

volumes:
  redis_data:

services:
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ./src:/var/www/html:cached
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php
  php:
    build:
      context: .docker/php
      dockerfile: php.local.dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html:cached
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    restart: unless-stopped
    command: redis-server --requirepass ${DOCKER_REDIS_PASSWORD}
